# Generated by Django 4.0.6 on 2022-07-31 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='./static/'),
        ),
    ]
